-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  full_name text,
  phone text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. MEMBERSHIPS (Tracks subscription status)
create type membership_tier as enum ('free', 'premium');
create type membership_status as enum ('active', 'inactive', 'past_due', 'cancelled');

create table public.memberships (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  tier membership_tier default 'free',
  status membership_status default 'active',
  stripe_subscription_id text, -- For future Stripe integration
  current_period_end timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. EVENTS (Dynamic event data)
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null, -- "Murph Adaptado"
  description text,
  date date not null,
  time time not null,
  location text not null,
  price decimal(10,2) default 0.00,
  max_spots int default 20,
  images text[], -- Array of image URLs
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. REGISTRATIONS (Who is going to what?)
create table public.registrations (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  event_id bigint references public.events(id) on delete cascade not null,
  status text default 'confirmed', -- confirmed, cancelled, waitlist
  lunch_option boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, event_id) -- Prevent double booking
);

-- 5. TRANSACTIONS (Payment history)
create type transaction_status as enum ('succeeded', 'pending', 'failed', 'refunded');

create table public.transactions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete set null,
  amount decimal(10,2) not null,
  currency text default 'eur',
  status transaction_status default 'pending',
  stripe_payment_id text,
  description text, -- "Mensualidad Premium" or "Drop-in Evento X"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES (Security)
alter table public.profiles enable row level security;
alter table public.memberships enable row level security;
alter table public.events enable row level security;
alter table public.registrations enable row level security;
alter table public.transactions enable row level security;

-- Profiles: Users can read/update their own profile
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Memberships: Users can read their own membership
create policy "Users can view own membership" on memberships for select using (auth.uid() = user_id);

-- Events: Publicly viewable
create policy "Events are viewable by everyone" on events for select using (true);

-- Registrations: Users can view/create their own
create policy "Users can view own registrations" on registrations for select using (auth.uid() = user_id);
create policy "Users can register themselves" on registrations for insert with check (auth.uid() = user_id);

-- Transactions: Users can view their own
create policy "Users can view own transactions" on transactions for select using (auth.uid() = user_id);

-- TRIGGER: Create profile and default membership on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  
  insert into public.memberships (user_id, tier, status)
  values (new.id, 'free', 'active');
  
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
